uoslife/client-meeting-season4

src/compents/inputs/TextInput.style.tsx, src/compents/inputs/TextInput.tsx, src/hooks/useInput.tsx
- Input 공통 컴포넌트를 제작했습니다.
**figma**
<br/>
<br/>
**현재까지 구현**
**Input 컴포넌트 속성 설명**
- status: default(기본), focused(input 클릭 시), filled(값이 있을 시), error(오류 생겼을 시)
- placeholder: input 칸 기본으로 있는 문구 (ex: "text", "웹메일 주소 입력" 등)
- onClick: 외부 훅 사용하여 컴포넌트 관리 (x 버튼 클릭 시 value 값 초기화)
- onChange: 외부 훅 사용하여 컴포넌트 관리 (추후 value 값 전달을 위함)
- isAuthentication: 인증번호 버튼 On/Off에 따라 X icon 표시
**이후 추가 예정**
- 글씨체
- icon
**테스트 코드**
```
//import GlobalStyle from '~/styles/GlobalStyle';
//import { css } from '@emotion/react';
import Button from './compents/buttons/Button';
import TextInput from './compents/inputs/TextInput';
import { useInput } from './hooks/useInput';
function App() {
const { inputValue, setValueClear, handleInputChange } = useInput('');
return (
<>
<TextInput
value={inputValue}
placeholder="text" …
```
=> feat: Input 공통 컴포넌트 제작

package.json, src/App.tsx, src/hooks/useFunnel.tsx, src/pages/personal/myInformationStep/FifthPage.tsx, src/pages/personal/myInformationStep/FirstPage.tsx, src/pages/personal/myInformationStep/ForthPage.tsx, src/pages/personal/myInformationStep/SecondePage.tsx, src/pages/personal/myInformationStep/SixthPage.tsx, src/pages/personal/myInformationStep/ThirdPapge.tsx, src/pages/personal/myInformationStep/index.tsx, src/routes/commonRoutes.tsx, src/routes/groupRoutes.tsx, src/routes/index.tsx, src/routes/personalRoutes.tsx, yarn.lock
- 페이지네이션 관리를 위해 useFunnel이라는 페이지네이션 전용 훅을 만들었습니다.
- 해당 훅이 사용되는 예시 페이지를 만들었습니다.
**useFunnel 훅에 사용되는 것을 보자면...**
=> feat(WEB-5): 페이지네이션 로직 훅(useFunnel) 제작

src/components/card/Card.tsx, src/components/layout/page/footer/Footer.style.ts, src/components/layout/page/footer/Footer.tsx
- Card의 패딩 구조를 수정하였습니다.
- Footer에서 bottom에도 border가 적용되도록 하였습니다. 변수명도 그에 맞게 고쳤습니다.
=> fix[WEB-36]: Card와 Footer 일부 스타일 수정

src/styles/colors.ts, src/styles/reset.ts
- LeferiBase 글꼴의 weight가 수정되지 않는 현상을 해결하기 위해 LeferiBaseBold 글꼴을 추가했습니다.
=> feat[WEB-42]: LeferiBase 글꼴 교체

src/components/inputs/dropdownInput/DropdownInput.style.tsx, src/components/inputs/dropdownInput/DropdownInput.tsx
- max-width를 삭제했습니다.
- 최상위 부모 요소의 width를 100%로 지정했습니다.
=> fix[WEB-44]: DropdownInput style 수정

src/pages/group/myInfomationStep/FirstPage.tsx, src/pages/group/myInfomationStep/SecondPage.tsx, src/pages/group/myInfomationStep/Step.tsx, src/store/meeting/common.ts
- 3:3 "나의 정보 입력하기" 팅장, 팅원 페이지를 제작했습니다.
<br/>
isLeader 값에 따라 팅장, 팅원 페이지로 분기 처리까지 완료했습니다.
=> feat[WEB-49]: 3:3 "나의 정보 입력하기" 팅장, 팅원 페이지 제작

src/components/buttons/roundButton/RoundButton.tsx, src/pages/common/univVerificationStep/FirstPage.tsx, src/pages/common/univVerificationStep/SecondPage.tsx, src/pages/common/univVerificationStep/Step.tsx, src/pages/common/univVerificationStep/ThirdPage.tsx
- "경희대·한국외대 구성원 인증" 서약 페이지 제작했습니다.
<br/>
- 첫 번째 페이지 버튼 활성화 처리 완료
- 두 번째 페이지 제작 완료
- 세 번째 페이지 경희대, 외대에 따라 이메일 분기 처리 완료
=> feat[WEB-62]: "경희대·한국외대 구성원 인증" 서약 페이지 제작

package.json, src/main.tsx, src/mocks/handlers.ts, src/mocks/worker.ts, yarn.lock
- msw 환경설정을 했습니다.
- API handler를 작성했습니다.
=> feat[WEB-61]: msw 환경설정

index.html
#모바일에서 input focus 시, 화면 줌인 현상 해결
- 모바일에서 input에 focust를 하면 화면이 줌인되는 현상이 있습니다.
- html 메타 태그를 추가해서 방지했습니다.
[문제 상황]
- 
https://github.com/uoslife/client-meeting-season4/assets/89263598/121c5dca-264e-4a3f-80a8-4c22dc2b9dc0
[해결]
-
https://github.com/uoslife/client-meeting-season4/assets/89263598/40d18eb9-0be6-4db0-84f7-72440fcc1b23
=> feat[WEB-71]: 모바일에서 input focus 시, 화면 줌인 현상 해결

src/api/services/meeting.ts, src/mocks/handlers.ts, src/models/group/data.ts, src/pages/group/leader/preferStep/FirstPage.tsx, src/pages/group/leader/preferStep/Step.tsx
- [PUT] api/meeting/${teamType}/${isTeamLeader}/prefer
- msw 환경에서의 axios api 연결을 완료하였습니다.
=> feat[WEB-76] 3:3 팅장 "선호 팅 정보 입력" API 연결

src/pages/common/paymentStep/PaymentPage.tsx, src/styles/reset.ts
- 포트원 리다이렉트 url 링크를 dev에 따라 localhost와 alpha 도메인으로 분기 처리 했습니다.
- 스크롤바를 제거해서 ux적인 불편함을 개선했습니다.
=> feat[WEB-86]: 포트원 리다이렉트 url 변경 및 스크롤바 제거

src/pages/common/landingStep/Step.tsx, src/types/icon.type.ts
=> [WEB-93] 사업자 정보 추가

src/components/modal/applicationModal/ApplicationModal.style.tsx, src/components/modal/applicationModal/ApplicationModal.tsx
- 신청 정보 확인하기 모달에 애니메이션을 추가했습니다.
=> [WEB-94] 신청 정보 확인하기 모달 애니메이션 추가

src/api/core/index.ts, src/api/services/auth.ts, src/api/services/meeting.ts, src/api/services/payment.ts, src/api/types/auth.type.ts, src/api/types/index.ts, src/main.tsx, src/pages/common/univVerificationStep/ThirdPage.tsx, vite.config.ts
- axios reponse type 수정했습니다.
- response interceptor error 추가하여 api 호출 실패 시, Promise.reject(error) 값을 받을 수 있습니다.
- 이메일 인증 api 로직을 일부 수정했습니다.
=> [WEB-97] axios reponse type 수정 및 response interceptor error 추가

src/pages/common/landingStep/Step.tsx
=> [M4FE-16] 사업자 등록번호 수정

src/pages/personal/myPreferTypeStep/Step.tsx, src/pages/personal/myRomanceStep/Step.tsx
- 포트원 심사를 위해 1대1 미팅에서 api error일 때, 페이지가 안넘거가게 짜여있는 api를 주석 처리 했습니다.
- 1대1 팅로맨스 업데이트 api 주석 처리
- 1대1 팅선호 업데이트 api 주석 처리
=> [M4FE-17] 포트원 심사를 위한 1대1 미팅 api 주석 처리

src/api/core/index.ts, src/components/modal/participationModal/ParticipationModal.style.tsx, src/components/modal/participationModal/ParticipationModal.tsx, src/pages/group/member/participateStep/FirstPage.tsx
- 팅원 코드 입력 api를 부착했습니다.
- M04 에러가 나는 경우 axios reponse interceptor을 통해 toast 메시지로 에러 대응을 합니다.
=> [M4FE-29] 3:3 팅원 코드 입력 api 부착

src/api/core/index.ts, src/pages/group/leader/createStep/SecondPage.tsx, src/pages/group/leader/myInfomationStep/Step.tsx, src/pages/group/member/myInformationStep/Step.tsx
=> [M4FE-36] 3:3 팅원 정보 입력 input 끊김 현상 해결

src/hooks/useFunnel.tsx, src/pages/common/branchGatewayStep/Step.tsx, src/pages/common/finishApplyStep/FirstPage.tsx, src/pages/common/paymentResultStep/Step.tsx, src/pages/common/paymentStep/PaymentPage.tsx, src/pages/common/paymentStep/Step.tsx, src/pages/common/univVerificationStep/Step.tsx, src/pages/group/leader/createStep/SecondPage.tsx, src/pages/group/member/participateStep/FirstPage.tsx, src/pages/group/roleSelectStep/Step.tsx, src/pages/personal/myInformationStep/Step.tsx, src/pages/personal/myRomanceStep/Step.tsx
- 3:3 팅원이 미팅 삭제하는 경우, 팅장 페이지에서 팀 삭제 toast 메시지 발생
- Step 컴포넌트 언마운트 시, Funnel 내부 자식 컴포넌트 리렌더링 버그 해결을 위한 useFunnel 의존성 제거
- 자잘한 문구 수정
- 팀 리셋 로직 적용
=> [M4FE-38] Step 컴포넌트 언마운트 시, 리렌더링 버그 해결

.npmrc, package.json, src/App.tsx, src/api/core/index.ts, src/api/services/auth.ts, src/bridge/index.ts, src/models/auth/index.ts, src/pages/common/branchGatewayStep/Step.tsx, src/pages/common/landingStep/Step.tsx, src/pages/group/leader/myInfomationStep/FirstPage.tsx, src/pages/group/leader/myInfomationStep/SecondPage.tsx, src/pages/group/member/myInformationStep/FirstPage.tsx, src/pages/group/member/myInformationStep/SecondPage.tsx, src/pages/personal/myInformationStep/FirstPage.tsx, src/pages/personal/myInformationStep/SecondPage.tsx, src/utils/silentLogin.ts, vite.config.ts, yarn.lock
- uoslifeBridge 설치
- 시대생 여부 전역값 추가
- 시대생 토큰값 만료 시, 앱으로 리다이렉트 로직 추가
- 시대생 로그인 api 추가
- 시대생일 때, silentLogin 재로그인 로직 추가
- 로그인 이후 미팅 종류 선택에서 뒤로 가기 시, 바로 Home으로 가게끔 라우팅 주소 변경
- 시대생일 경우, 홈화면 헤더 뒤로가기 추가
- 시대생일 경우, 시대생 로그인 api 로직 추가
- 시대생일 경우, 기존 시대생 앱 정보에서 갖고 온 정보를 내 정보에 추가
=> [M4FE-21] 웹뷰 브릿지 작업

src/api/services/payment.ts, src/components/modal/applicationModal/ApplicationModal.tsx, src/pages/common/checkApplyInfoStep/Step.tsx, src/pages/common/landingStep/Step.tsx, src/pages/common/univVerificationStep/Step.tsx, src/pages/common/univVerificationStep/ThirdPage.tsx
- 모달 문구 변경
- 결제 여부 확인 api 추가
- 결제 여부 확인 로직 추가
- 결제 성공 시, 이메일 재인증 이후 라우팅 로직 수정
=> [M4FE-40] 결제 여부 확인 api 로직 추가

src/components/layout/page/header/Header.tsx, src/components/modal/cleanUpModal/CleanUpModal.tsx, src/pages/common/landingStep/Step.tsx
=>  [M4FE-46]: 리셋 버튼 필수 부분 적용

src/api/core/index.ts, src/api/services/auth.ts, src/main.tsx, src/pages/common/branchGatewayStep/FirstPage.tsx, src/pages/common/branchGatewayStep/Step.tsx, src/pages/common/landingStep/Step.tsx, src/pages/common/paymentResultStep/Step.tsx, src/pages/common/paymentStep/PaymentPage.tsx, src/pages/common/univVerificationStep/ForthPage.tsx, src/pages/common/univVerificationStep/SecondPage.tsx, src/pages/group/leader/createStep/SecondPage.tsx, src/pages/group/leader/createStep/Step.tsx, src/pages/group/leader/groupInformationStep/Step.tsx, src/pages/group/leader/myInfomationStep/Step.tsx, src/pages/group/leader/preferStep/Step.tsx, src/pages/group/member/myInformationStep/Step.tsx, src/pages/personal/myInformationStep/Step.tsx, src/pages/personal/myRomanceStep/Step.tsx
=> [M4FE-48] 어카운트 추가

index.html
=> feat: Meta Pixel 추가

index.html, package.json, src/hooks/usePageTracking.tsx, src/routes/index.tsx, tsconfig.json, yarn.lock
react-router-dom 에서 location 변경 이벤트를 감지해서 보고하도록 hook을 짜두었으나,
상세 이벤트 수집은 조금 더 논의 후에 추가해주세요~
Closes #127
=> feat: Google Analytics 추가

index.html, package.json, src/App.tsx, src/hooks/usePageTracking.tsx, src/main.tsx, src/routes/index.tsx, src/styles/reset.ts, src/styles/typographies.ts, tsconfig.json, yarn.lock
- Gothic A1 (400, 700)
- Pretendard (100~900)
- Leferi Base (400, 700)
- Neo 둥근모 Pro (400)
- DOS 고딕 (400)
Closes #154
=> fix: 웹폰트 외부 CDN으로 변경
